- hosts: backends
  remote_user: ubuntu

  tasks:
    - block:
      - name: Update packages
        apt:
          update_cache: yes
      - name: Upgrade packages
        apt:
          name: "*"
          state: latest
          force_apt_get: true
      - name: Autoremove packages
        apt:
          autoremove: yes
      become: yes
      become_method: sudo

    - block:
      - name: Clone repo
        git:
          repo: 'https://github.com/decentraland/marketplace.git'
          dest: /home/ubuntu/app
          version: master

    - block:
      - name: Install 
        get_url: 
          url: https://deb.nodesource.com/setup_8.x
          dest: /tmp/nodesource_setup.sh
      - name: Use magic
        shell: bash /tmp/nodesource_setup.sh
      - name: Update packages
        apt:
          update_cache: yes
      - name: Install the nodejs
        apt:
          name: nodejs
          state: present
      become: yes
      become_method: sudo
